@startuml C4_Container
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь")
System_Ext(home1, "Дом 1", "Реле и датчики температуры")
System_Ext(home2, "Дом 2", "Реле и датчики температуры")

System_Boundary(softwareSystem, "Тёплый дом — система управления") {

  Container(webApp, "Web", "Личный кабинет", "Информация о подключенных датчиках / управление температурой")
  Container(apiApp, "Backend Application", "Go", "Бизнес логика")
  ContainerDb(database, "PostgreSQL", "Пользователи, датчики, счета итд")
}

' Воображаемая система оплат
System_Ext(billingSystem, "Billing System", "Генерация счетов, прием и проверка оплат")

Rel(user, webApp, "Проверка температуры, управление отоплением")
Rel(webApp, apiApp, "API вызовы")
BiRel(apiApp, database, "Чтение и запись")
Rel(apiApp, billingSystem, "Биллинг")
BiRel(apiApp, home1, "Wi-Fi", "Управление датчиками / Регистрация датчиков при включении")
BiRel(apiApp, home2, "Wi-Fi", "Управление датчиками / Регистрация датчиков при включении")

@enduml