syntax = "proto3";

package notification;

option go_package = "github.com/achrt/architecture-warmhouse/notification/api;notificationpb";

message Id {
  bytes id = 1;
}

enum NotificationChannel {
  CHANNEL_UNSPECIFIED = 0;
  CHANNEL_EMAIL = 1;
  CHANNEL_PUSH = 2;
}

message Notification {
  Id id = 1;
  Id user_id = 2;
  string title = 3;
  string message = 4;
  NotificationChannel channel = 5;
  bool delivered = 6;
  int64 timestamp = 7;
}

message SendNotificationRequest {
  Id user_id = 1;
  string title = 2;
  string message = 3;
  NotificationChannel channel = 4;
}

message SendNotificationResponse {
  Notification notification = 1;
}

service NotificationService {
  rpc SendNotification(SendNotificationRequest) returns (SendNotificationResponse);
}
